services:
  - type: web
    name: aura-food-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: AI-Based Food Redistribution System
      - key: APP_VERSION
        value: 1.0.0
      - key: DEBUG
        value: "false"
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: food_redistribution
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
